// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/65ab1926ba6288f9371ae094
###
GET http://localhost:8080/contacts/65ab1acdba6288f9371ae097
###
GET http://localhost:8080/contacts/65ab1bb3ba6288f9371ae098

// PRODUCTION Deploy
###
GET https://test-solution2.onrender.com/contacts
###
GET https://test-solution2.onrender.com/contacts/65ab1926ba6288f9371ae094
###
GET https://test-solution2.onrender.com/contacts/65ab1acdba6288f9371ae097
###
GET https://test-solution2.onrender.com/contacts/65ab1bb3ba6288f9371ae098
