// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/65ab1926ba6288f9371ae094
###
GET http://localhost:8080/contacts/65ab1acdba6288f9371ae097
###
GET http://localhost:8080/contacts/65ab1bb3ba6288f9371ae098

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
